### ISSUE TITLE
Unable to 'Show History' - Problems while loading file history: HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by thecesrom** [Microsoft/vso-intellij#140]
Plugin version: 1.134.0
TEE-CLC: 14.134.0
OS: Windows 10 and macOS
IDE: Pycharm 2018.1.2

I am able to connect to VSTS and create a local workspace.  Hosted at https://{mycompany}.visualstudio.com, but whenever I add the VSTS project as a dependency on another project, all TFVC functionality ceases to work.

Under **Settings > Version Control** the VSTS project appears correctly, but when I try to 'Show History' I get an error message saying: **Problems while loading file history: HTTP 401 Unauthorized**.

If I open the project by itself, all TFVC functionality works as expected; it is only when I add the project as a dependency that it does not work.  If I right-click on the project and choose **TFVC > Edit Workspace..**, there is **Nothing to show**.

**Comment by TheConstructor** [comment]
Got the same from within DataGrip 2018.2 EAP
Build #DB-182.3684.15, built on July 12, 2018
DataGrip EAP User
Expiration date: August 11, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

I have 3 directories attached, which are located in 2 different workspaces of the same TFS-TFVC repository. Updating folders seems to work, but showing history does not.

**Comment by moonheart** [comment]
I think this is caused by Server path is root, and the ide cannot get `teamProjectName` as #250 said.

I created two workspaces in rider:

Status|Server path|Local Path
---|---|---
MAPPED|$/ProjectsA|D:\src\ProjectA

In the first workspace, everything is working as expected.

Status|Server path|Local Path
---|---|---
MAPPED|$/|D:\src2\

In the second workspace, file history cannot be retrived, error message: `Problems while loading file history: HTTP 401 Unauthorized`.

**Comment by ForNeVeR** [comment]
@moonheart, thanks for your investigation. Yes, we may have some troubles in cases when the root folder (aka `$/`) is mapped directly. Some of these issues were fixed, but some still aren't.

I'll take a look at the first opportunity.

**Comment by erikhubers** [comment]
I switched from the (now unsupported) Intellij TFS plugin to the azure-devops-intellij one. This issue still seems to be occuring in the latest version (1.160.0). I remember this being an issue a few years back in the [Intellij TFS plugin ](https://plugins.jetbrains.com/plugin/4578-tfs). On a sidenote, I also remember not being able to annotate on a local workspace and no recognized mapping at all using a server workspace. Which is a similar issue I'm having right now during transition. Is this a (very) early fork of the Intellij TFS plugin perhaps?

**Comment by ForNeVeR** [comment]
Detailed bug report would help. What were you trying to do, screenshots of important steps, and IDE logs.

This is an early fork of the original TFS plugin, but I don't believe any significan amount of the original sources still reside in the plugin, so this issue is likely a new one.

Regarding the server workspaces: we have finished working on initial support; the next plugin release will include this functionality.

**Comment by rajeshaz09** [comment]
@ForNeVeR  I am facing the same problem on Android Studio on Mac. I can help you providing more info. Could you tell me what info do you need? and steps to collect?
I just installed latest version today and i got same error.
